from django.urls import path
from .views import (
    home,
    signup_view,
    login_view,
    logout_view,
    predict_view,
    dashboard_view,
    history_view,
    market_prices_view,
    farming_tips_view,
    crop_calendar_view,
    profile_view,
    weather_api_view,
    agromonitoring_api_view,
    report_view,
    # Tier-1 features
    fertilizer_view,
    cost_calculator_view,
    district_benchmark_view,
    ajax_get_districts,
    trends_view,
    tn_analytics_view,
    # Tier-2 features
    yield_predictor_view,
    global_yield_view,
    rice_disease_view,
    soybean_disease_view,
    pesticide_analysis_view,
    # Tier-3 features
    global_agriculture_view,
    irrigation_advisor_view,
    rotation_planner_view,
    soil_tracker_view,
    corn_comparison_view,
    food_security_view,
    # Tier-4 features
    climate_forecast_view,
    anomaly_detection_view,
    portfolio_optimizer_view,
)

urlpatterns = [
    path('',                        home,                    name='home'),
    path('signup/',                 signup_view,             name='signup'),
    path('login/',                  login_view,              name='login'),
    path('logout/',                 logout_view,             name='logout'),
    path('predict/',                predict_view,            name='predict'),
    path('dashboard/',              dashboard_view,          name='dashboard'),
    path('history/',                history_view,            name='history'),
    path('market-prices/',          market_prices_view,      name='market_prices'),
    path('farming-tips/',           farming_tips_view,       name='farming_tips'),
    path('crop-calendar/',          crop_calendar_view,      name='crop_calendar'),
    path('profile/',                profile_view,            name='profile'),
    path('api/weather/',            weather_api_view,        name='weather_api'),
    path('api/satellite/',          agromonitoring_api_view, name='satellite_api'),
    path('report/<int:pk>/',        report_view,             name='report'),
    # Tier-1
    path('fertilizer/',             fertilizer_view,         name='fertilizer'),
    path('cost-calculator/',        cost_calculator_view,    name='cost_calculator'),
    path('district-benchmark/',     district_benchmark_view, name='district_benchmark'),
    path('tn-analytics/',           tn_analytics_view,       name='tn_analytics'),
    path('trends/',                 trends_view,             name='trends'),
    path('api/districts/',          ajax_get_districts,      name='ajax_districts'),
    # Tier-2
    path('yield-predictor/',        yield_predictor_view,    name='yield_predictor'),
    path('global-yield/',           global_yield_view,       name='global_yield'),
    path('disease-detect/',         rice_disease_view,       name='rice_disease'),
    path('soybean-disease/',        soybean_disease_view,    name='soybean_disease'),
    path('pesticide-analysis/',     pesticide_analysis_view, name='pesticide_analysis'),
    # Tier-3
    path('global-agriculture/',     global_agriculture_view, name='global_agriculture'),
    path('irrigation-advisor/',     irrigation_advisor_view, name='irrigation_advisor'),
    path('rotation-planner/',       rotation_planner_view,   name='rotation_planner'),
    path('soil-tracker/',           soil_tracker_view,       name='soil_tracker'),
    path('corn-comparison/',        corn_comparison_view,    name='corn_comparison'),
    path('food-security/',          food_security_view,      name='food_security'),
    # Tier-4
    path('climate-forecast/',       climate_forecast_view,   name='climate_forecast'),
    path('anomaly-detection/',      anomaly_detection_view,  name='anomaly_detection'),
    path('portfolio-optimizer/',    portfolio_optimizer_view, name='portfolio_optimizer'),
]
